import localFont from "next/font/local";
import "./globals.css";
import { UserProvider } from "@/utils/UserContext";
import AuthLayout from "./component/AuthLayout";
import NavBar from "./component/NavBar";
import FooterSection from "./component/FooterSection";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Kuldeep Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <NavBar />
          {children}
          <FooterSection />
        </UserProvider>
      </body>
    </html>
  );
}
